kramdown:
  input: GFM
  hard_wrap: false

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:       Mvc5 Framework
keywords:    Dependency Injection, Inversion of Control, Events, Named Arguments, Service Providers, Console Applications
description: An enhanced PHP programming environment that provides inversion of control of a web application or any function
url:         http://mvc5.github.io
baseurl:     ''

# About/contact
author:
  name:              devosc
  url:               https://twitter.com/devosc
  email:             devosc@gmail.com
