version: '3.5'

networks:
  public:
    external:
      name: traefik_webgateway

services:
  app:
    command: jekyll serve
    container_name: mvc5-github-pages
    environment:
      - JEKYLL_UID=${USER_ID}
      - JEKYLL_GID=${GROUP_ID}
    image: jekyll/jekyll
    labels:
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:mvc5-github-pages
      - traefik.port=4000
    networks:
      - public
    volumes:
      - .:/srv/jekyll
      - ./bundle:/usr/local/bundle
